---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Ensure APT package cache is updated
      ansible.builtin.apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 86400

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name: "{{ dependency }}"
        state: present
      loop: "{{ omz_dependencies }}"
      loop_control:
        loop_var: dependency

    - name: Create test users for role testing
      ansible.builtin.user:
        name: "bob"
        shell: /bin/bash
        state: present

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      zsh:
        write_file: true
        change_shell: true
      omz:
        install: true
        user: bob
        plugins:
          - git
          - zsh-autosuggestions
