---
- name: Converge
  hosts: all

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      zsh:
        write_file: true
        change_shell: true
      omz:
        install: true
        user: bob
        plugins:
          - git
          - zsh-autosuggestions
