---
- name: Prepare
  hosts: all
  tasks:
    - name: Load role vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/vars/main.yml"

    - name: Ensure APT package cache is updated
      ansible.builtin.apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 86400

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name: "{{ dependency }}"
        state: present
      loop: "{{ omz_dependencies }}"
      loop_control:
        loop_var: dependency

    - name: Create test users for role testing
      ansible.builtin.user:
        name: "bob"
        shell: /bin/bash
        state: present
