name: Lint

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened

concurrency:
    group: lint-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:

            - name: Checkout the current branch
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

            - name: Run ansible-lint linting command
              uses: ansible/ansible-lint@5fac056c45595896c973fbde871f01f6cb14d74c
